name: Collect DORA Metrics

on:
  workflow_dispatch:

jobs:
  collect-metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run metrics collector
      run: node scripts/collect_metrics.js

    - name: Upload metrics artifact
      uses: actions/upload-artifact@v4
      with:
        name: dora-metrics
        path: metrics.json
